/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ClerkDevAccountDefaultEndpoint": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkJWTAuthorizer": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Frontend": {
      "type": "sst.aws.Astro"
    }
    "Notes": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}